version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/traefik-tls.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.options=default@file"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.websafe.acme.email=test@example.com"
      - "--certificatesresolvers.websafe.acme.storage=/cert/acme.json"
      - "--certificatesresolvers.websafe.acme.httpchallenge.entrypoint=web"
    labels:
      - "traefik.http.routers.traefik.middlewares=traefik-compress"
      - "traefik.http.middlewares.traefik-compress.compress=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik-tls.yml:/etc/traefik/traefik-tls.yml
      - traefik_certs:/cert

  backend:
    image: ghcr.io/mhorst00/websafe-backend:latest
    container_name: "backend"
    restart: always
    environment:
      - DB_URL=backend-db
    env_file:
      - api.env
    volumes:
      - backend_safe:/code/safe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`gruppe4.testsites.info`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix,secHeaders@file"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api/v1"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=websafe"

  frontend:
    image: ghcr.io/mhorst00/websafe-frontend:latest
    container_name: "frontend"
    restart: always
    environment:
      - REACT_APP_DOMAIN=https://gruppe4.testsites.info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gruppe4.testsites.info`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.middlewares=secHeaders@file,frontend-compress"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=websafe"
      - "traefik.http.middlewares.frontend-compress.compress=true"

  db:
    image: mongo
    restart: always
    container_name: backend-db
    volumes:
      - backend_db:/data/db

volumes:
  traefik_certs:
  backend_safe:
  backend_db:
