name: Backend Unit Tests

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    types: [opened]
    paths:
      - "backend/**"

jobs:
  unittests:
    runs-on: ubuntu-latest
    name: Unit Tests
    services:
      mongodb:
        image: mongodb
        ports:
          - 27017:27017
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10 environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend
      - name: unittest Tests
        run: python -m unittest discover
        working-directory: ./backend